language: generic

env:
- GIT_SSH="/tmp/ssh"

after_success:
- echo -e '#!/bin/sh\n\nssh -o StrictHostKeyChecking=no $*' >> /tmp/ssh
- chmod a+x /tmp/ssh

- openssl aes-256-cbc -K $encrypted_22fd8ae6a707_key -iv $encrypted_22fd8ae6a707_iv
          -in .travis/deploy_key.enc -out .travis/deploy_key -d
- chmod 600 .travis/deploy_key

- eval "$(ssh-agent -s)"
- ssh-add .travis/deploy_key

- git config user.name "CI Bot"
- git config user.email "nextcloud-snappy-bot@git.launchpad.net"
- git remote add deploy git+ssh://nextcloud-snappy-bot@git.launchpad.net/nextcloud-snap

- test "$TRAVIS_EVENT_TYPE" != "cron" && .travis/deploy.sh
- test "$TRAVIS_EVENT_TYPE" = "cron"  && .travis/cron.sh
